# Executable names:
EXE = final
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = graph.o draw.o shortestpath.o main.o 

# Use the cs225 makefile template:
include cs225/make/cs225.mk
