apiVersion: batch/v1
kind: Job
metadata:
  generateName: freeservice
spec:
  template:
    spec:
      containers:
      - name: mp12free
        image: diomou4/mp12_docker:mp12Tag
        resources:
          limits:
            cpu: "0.9"
          requests:
            cpu: "0.9"
        env:
        - name: DATASET
          value: "mnist"
        - name: TYPE
          value: "ff"
      restartPolicy: Never
  backoffLimit: 2
